BOARD_VENDOR = zte
TARGET_DEVICE = n5

TARGET_SPECIFIC_HEADER_PATH := $(LOCAL_DIR)/include
TARGET_BOARD_PLATFORM := msm8960
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
#TODO TARGET_KERNEL_SOURCE := kernel/$(BOARD_VENDOR)/$(TARGET_DEVICE)
#TODO TARGET_KERNEL_CONFIG := $(TARGET_DEVICE)_defconfig

# Disabled
USE_CAMERA_STUB := true

# Board / Kernel Setup
TARGET_ARCH := arm
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp -DQCOM_SSR_ENABLED
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := krait
ARCH_ARM_HAVE_TLS_REGISTER := true
BOARD_KERNEL_BASE := 0x80200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x02000000
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000



# Krait Optimizations
TARGET_USE_KRAIT_BIONIC_OPTIMIZATION := true
TARGET_USE_KRAIT_PLD_SET := true
TARGET_KRAIT_BIONIC_PLDOFFS := 10
TARGET_KRAIT_BIONIC_PLDTHRESH := 10
TARGET_KRAIT_BIONIC_BBTHRESH := 64
TARGET_KRAIT_BIONIC_PLDSIZE := 64

# Audio
BOARD_USES_ALSA_AUDIO := true
BOARD_USES_FLUENCE_INCALL := true
BOARD_USES_LIBMEDIA_WITH_AUDIOPARAMETER	:= true
TARGET_QCOM_AUDIO_VARIANT := caf

# Bootloader
BOARD_WANTS_EMMC_BOOT := true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOOTLOADER_BOARD_NAME := n5
TARGET_BOOTLOADER_NAME= n5

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
BLUETOOTH_HCI_USE_MCT := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/$(BOARD_VENDOR)/$(TARGET_DEVICE)/bluetooth/

# Camera
#TARGET_PROVIDES_CAMERA_HAL := true

# Flags
BOARD_USES_QCOM_HARDWARE := true
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE



# Preload bootanimation
TARGET_BOOTANIMATION_PRELOAD := true



# Graphics
BOARD_EGL_CFG := device/$(BOARD_VENDOR)/$(TARGET_DEVICE)/configs/egl.cfg
COMMON_GLOBAL_CFLAGS += -DQCOM_NO_SECURE_PLAYBACK
BUILD_EMULATOR_OPENGL := false
TARGET_NO_HW_VSYNC := true
TARGET_USES_C2D_COMPOSITION := true
BOARD_EGL_NEEDS_LEGACY_FB := true
USE_OPENGL_RENDERER := true
TARGET_USES_ION := true
TARGET_USES_OVERLAY := true
TARGET_USES_SF_BYPASS := true

# GPS
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := $(TARGET_BOARD_PLATFORM)
TARGET_NO_RPC := true

# Recovery
BOARD_HAS_NO_SELECT_BUTTON := true
# BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"

# USB
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/msm_hsusb/gadget/lun%d/file


# Wifi
BOARD_HAS_QCOM_WLAN := true
BOARD_WLAN_DEVICE := qcwcn
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
WIFI_DRIVER_MODULE_NAME := "wlan"
WIFI_DRIVER_MODULE_PATH := "/system/lib/modules/wlan.ko"
WIFI_DRIVER_FW_PATH_STA := "sta"
WIFI_DRIVER_FW_PATH_AP := "ap"

# Filesystem
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 805306368
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
BOARD_VOLD_MAX_PARTITIONS := 36

TARGET_PREBUILT_KERNEL := device/zte/n5/kernel

# Additional build config
BOARD_USES_SECURE_SERVICES := true
BOARD_CHARGER_ENABLE_SUSPEND := true

# Webkit
ENABLE_WEBGL := true 
TARGET_FORCE_CPU_UPLOAD := true

BOARD_CUSTOM_GRAPHICS := ../../../device/zte/n5/recovery_en/graphics.c
BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/zte/n5/recovery_en/recovery_ui.c
TARGET_PREBUILT_RECOVERY_KERNEL := device/zte/n5/recovery_kernel
TARGET_RECOVERY_INITRC := device/zte/n5/recovery_en/recovery.rc
TARGET_RECOVERY_FSTAB := device/zte/n5/recovery.fstab
